export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Login types....
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"; 
export const LOGIN_FAILURE = "LOGIN_FAILURE"; 
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"; 
export const UPDATE_WATCHLIST = "UPDATE_WATCHLIST"; 

export const SET_USER = "SET_USER"; 
export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST"; 
export const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST"; 
export const RESET_FROM_WATCHLIST = "RESET_FROM_WATCHLIST"; 
//Get Movies types....
export const GET_SEARCH_MOVIES_REQUEST = "GET_SEARCH_MOVIES_REQUEST"; 
export const GET_SEARCH_MOVIES_SUCCESS = "GET_SEARCH_MOVIES_SUCCESS"; 
export const GET_SEARCH_MOVIES_RESET = "GET_SEARCH_MOVIES_RESET"; 
export const GET_SEARCH_MOVIES_FAILURE = "GET_SEARCH_MOVIES_FAILURE"; 
//Get Movies details types....
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";


